### ISSUE TITLE
Can I use the [Config] inside another class than a function

### ISSUE THREAD

**Issue by JulienCroain** [daulet/Indigo.Functions#1]
Hello,

I try to inject a settings inside a dependency but it doesn't work:

`public FunctionConfiguration([Config("myConnectionString")] string myConnectionString)`

But when I try on my function, it works:

```[FunctionName("myFunction")]
public static void Run([EventHubTrigger(...)] string myEventHubMessage,
            [Config("myConnectionString")] string myConnectionString,
            TraceWriter log)
```

Have you an idea ?

Thank you !

**Comment by daulet** [comment]
Hi,

Unfortunately that does not work currently - I'd also love to be able to declare bindings somewhere in dependency tree.

When you use [Config] in function declaration, corresponding parameter value is resolved by Azure WebJobs at runtime. Using it in constructor does not do anything unless you have a DI manager that respects the binding. I already have another [binding](https://github.com/daulet/Indigo.Functions#dependency-injection) that supports DI, I could probably figure out how to combine the two.

**Comment by daulet** [comment]
I was inspired by this [article](http://autofac.readthedocs.io/en/latest/faq/injecting-configured-parameters.html#option-2-use-a-provider) and I decided to solve this by injecting IConfiguration instance. See [this sample](https://github.com/daulet/Indigo.Functions/blob/master/sample/AutofacFunctionSample/ICacheConfigProvider.cs) for example. Essentially the recommendation is to use a provider class that is responsible for actually reading values from Application Settings via IConfiguration. So for this problem I'd recommend using [dependency injection binding](https://github.com/daulet/Indigo.Functions#dependency-injection) instead of [configuration binding](https://github.com/daulet/Indigo.Functions#configuration).

**Comment by JulienCroain** [comment]
Thank you !
